spring.application.name=music

# DB 서버 연동 정보
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/musicdb
spring.datasource.username=musicdb
spring.datasource.password=12345

# MySQL dialect 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 테이블 자동 생성 여부
spring.jpa.hibernate.ddl-auto=create
# 생성되는 SQL 구문 출력 여부
spring.jpa.show-sql=true
# SQL 구문 예쁘게 출력
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# 로그 출력(개발용)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace